### PR TITLE
Fix ability for `ConvertFrom-ArmTemplate` to accept relative path (or wildcards)

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Need to resolve the path parameter value otherwise relative paths are not relative to current location (also affects ability to use wildcards to match files)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
Don't know why build isn't able to find the nupkgs unrelated to my change...

**Comment by rjmholt** [comment]
I believe this is implemented by https://github.com/PowerShell/PSArm/pull/136/

**Comment by rjmholt** [comment]
If you'd like to open a PR on that branch with your added test, that might be handy

**Comment by SteveL-MSFT** [comment]
will add commit with test to your PR

**Pull request closed without merging**
